<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>danh sách các trường</title>
    
    <style>
        #div1 {
            background: yellowgreen;
            width: 500px;
            height: 40px;
        }
        #div2 {
            background: yellow;
            width: 500px;
            height: 39px;
            float: left;
        }
        #div3 {
            background: forestgreen;
            width: 200px;
            height: 50px;
            float: right;
        }
        .class1 {
            margin: 5px;
            padding: 6px;
            border: solid 1px firebrick;
        }

    </style>
</head>
<body>
    
    <fieldset>
        <legend><h1><div id="div1">danh sách các trường đại học</div></h1></legend>
        <h3> link này dành cho các bạn xét nguyện vọng vào các trường  đại học link ko có độc hại các bạn có thể thoải mái xem </h3>
        <img width="500px" height="500px" src="https://image2.tin247.news/pictures/2021/08/07/lcq1628290283.jpg" alt="good luck" title="good luck">
    </fieldset>


<fieldset>
        <h1><div id="div2">Các trường ĐH Ở TP Hồ chí minh</div></h1>
        <br />
        <br />
        <br />
        <h3><a href="https://www.vanlanguni.edu.vn/" class="class1"> văn lang University </a></h3>
        <img width="300px" src="https://dean1665.vn/uploads/school/van-lang.jpg" alt="văn lang University" title="văn lang University">
        <br />
        <h3><a href="https://vhu.edu.vn/" class="class1"> văn hiến University</a></h3>
        <img width="300px" src="https://allimages.sgp1.digitaloceanspaces.com/tipeduvn/2022/01/1641277764_683_Top-5-Truong-dao-tao-nganh-Quan-he-cong-chung.jpg" alt=" văn hiến University" title=" văn hiến University">
        <br />
        <h3><a href="https://www.hutech.edu.vn/" class="class1"> hutech University</a></h3>
        <img width="300px" src="https://file1.hutech.edu.vn/file/editor/homepage1/1.%20To%C3%A0n%20c%E1%BA%A3nh%20-%20Trung%20t%C3%A2m%20%C4%90%C3%A0o%20t%E1%BA%A1o%20nh%C3%A2n%20l%E1%BB%B1c%20ch%E1%BA%A5t%20l%C6%B0%E1%BB%A3ng%20cao%20%285%29.JPG" alt="hutech University" title="hutech University">
        <br />
        <h3><a href="https://www.rmit.edu.vn/" class="class1">RIMT University</a></h3>
        <img width="300px" src="https://www.rmit.edu.au/content/dam/rmit/vn/en/assets-for-production/images/rmit-sgs-campus-facilities/2019-campus-photos/sgs-campus-night-05.jpg" alt="RIMT University" title="RIMT University">
        <br />
        <h3><a href=" http://www.tdtu.edu.vn/" class="class1">Tôn Đức Thắng University</a></h3>
        <img width="300px" src="https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2020/10/18/846363/Tonducthang.jpg" alt="Tôn Đức Thắng University" title="Tôn Đức Thắng University">
        <br />
        <h3><a href="http://www.hcmuaf.edu.vn/" class="class1"> Nông Lâm University</a></h3>
        <img width="300px" src="https://danviet.mediacdn.vn/2021/3/12/h-nong-lam-1615538881496431289904.jpg" alt="Nông Lâm University" title="Nông Lâm University">
        <br />
        <h3><a href=" http://www.ueh.edu.vn/"class="class1"> Kinh Tế University TP Hồ chí minh</a></h3>
        <img width="300px" src="https://ueh.edu.vn/images/upload/thumbnail/ueh-thumbnail-021221-080521.jpg" alt="Kinh Tế University TP Hồ chí minh" title="Kinh Tế University TP Hồ chí minh">
        <br />
        <h3><a href="https://www.uit.edu.vn/"class="class1"> Đại học Công nghệ thông tin Tp Hồ Chí Minh</a></h3>
        <img width="300px" src="http://media.doisongphapluat.com/684/2021/1/14/vi-sao-truong-dh-cong-nghe-thong-tin-dh-quoc-gia-tphcm-cho-sinh-vien-nghi-tet-den-49-ngay-dspl-2.jpg" alt="Đại học Công nghệ thông tin Tp Hồ Chí Minh" title="Đại học Công nghệ thông tin Tp Hồ Chí Minh">
        <br />
        <h3><a href="https://www.hcmiu.edu.vn/"class="class1">Đại học quốc gia TP Hồ Chí Minh</a></h3>
        <img width="300px" src="https://cdnimg.vietnamplus.vn/t620/uploaded/pcfo/2019_06_19/1906_dhqgvtv.jpg" alt="Đại học quốc gia TP Hồ Chí Minh" title="Đại học quốc gia TP Hồ Chí Minh">
        <br />
        <h3><a href="https://www.hcmus.edu.vn/" class="class1"> Đại học khoa học tự nhiên TP Hồ Chí Minh</a></h3>
        <img width="300px" src="https://tuyensinh.tvu.edu.vn/uploads/news/2018_08/dh-kh-tu-nhien-tphcm-aczc.jpg" alt="Đại học khoa học tự nhiên TP Hồ Chí Minh" title="Đại học khoa học tự nhiên TP Hồ Chí Minh">
        <br />
        <h3><a href="http://www.yds.edu.vn"class="class1"> Đại học Y TP Hồ Chí Minh </a></h3>
        <img width="300px" src="http://chamsockhachang.com/wp-content/uploads/dai-hoc-y-duoc-tp.hcm_.jpg" alt="Đại học Y TP Hồ Chí Minh" title="Đại học Y TP Hồ Chí Minh">
        <br />
        <h3><a href="https://hoasen.edu.vn/vi"class="class1"> Hoa Sen University</a></h3>
        <img width="300px" src="https://huongnghiep.hocmai.vn/wp-content/uploads/2021/12/DH-Hoa-sen-2.jpg" alt="Hoa Sen University" title="Hoa Sen University">
        <br />
        <h3><a href=" http://ntt.edu.vn/web/"class="class1"> Nguyễn Tất Thành University</a></h3>
        <img width="300px" src="https://sotaytuyensinh.vn/uploads/dai-hoc-nguyen-tat-thanh.png" alt=" Nguyễn Tất Thành University" title=" Nguyễn Tất Thành University">
        <br />
        <h3><a href="http://www.hcmulaw.edu.vn/" class="class1"> Đại học luật TP Hồ Chí Minh</a></h3>
        <img width="300px" src="https://tuyensinhso.vn/images/files/tuyensinhso.com/truong-dai-hoc-luat-tp-hcm-1.jpg" alt="Đại học luật TP Hồ Chí Minh" title="Đại học luật TP Hồ Chí Minh">

        <br />
        <h3><a href="http://iuh.edu.vn/" class="class1">ĐẠI HỌC CÔNG NGHIỆP TP. HỒ CHÍ MINH</a></h3>
        <img width="300px" src="https://trangtuyensinh.com.vn/wp-content/uploads/2022/02/truong-dai-hoc-cong-nghiep-tphcm-phan-hiu-da-nang-trang-tuyen-sinh.jpg" alt="ĐẠI HỌC CÔNG NGHIỆP TP. HỒ CHÍ MINH" title="ĐẠI HỌC CÔNG NGHIỆP TP. HỒ CHÍ MINH">
        <br /> 
        <h3><a href="http://cs2.ftu.edu.vn/" class="class1">Đại học Ngoại thương</a></h3>
        <img width="300px" src="https://cafebiz.cafebizcdn.vn/thumb_w/600/162123310254002176/2020/10/4/photo1601807810595-1601807810724488808498.png" alt="Đại học Ngoại thương" title="Đại học Ngoại thương">
        <br />
        
    </fieldset>



    <fieldset>
        <h1><div id="div2">Các trường ĐH Ở TP Hà nội</div></h1>
        <br />
        <br />
        <br />
        <h3><a href="https://www.hust.edu.vn/" class="class1">Đại Học Bách Khoa </a></h3>
        <img width="300px" src="https://vcdn-vnexpress.vnecdn.net/2022/07/28/DHBKHN-6920-1658994052.jpg" alt="Đại học Bách khoa Hà nội" title="Đại học bách Khoa Hà Nội">
        <br />
        <h3><a href="https://hlu.edu.vn/" class="class1"> Đại Học Luật</a></h3>
        <img width="300px" src="https://intecovietnam.vn/wp-content/uploads/2020/05/HLU.jpg" alt="Đại học luật" title="Đại học luật">
        <br />
        <h3><a href="http://hus.vnu.edu.vn/" class="class1"> Khoa Học Tự Nhiên University </a></h3>
        <img width="300px" src="https://topsinhvien.vn/wp-content/uploads/2021/02/tu.jpg" alt="Đại học khoa học tự nhiên " title="Đại học khoa học tự nhiên">
        <br />
        <h3><a href="https://hmu.edu.vn/" class="class1"> Đại học Y Hà Nội </a></h3>
        <img width="300px" src="https://cdyhn.edu.vn/wp-content/uploads/2019/05/diem-chuan-dai-hoc-y-ha-noi.jpg" alt=" Đại học Y Hà Nội" title="Đại Học Y Hà Nội">
        <br />
        <h3><a href="https://hcmussh.edu.vn/" class="class1"> Đại Học xã hội và nhân văn</a></h3>
        <img width="300px" src="https://images.baodantoc.vn/uploads/2021/Th%C3%A1ng%207/untitled%20folder%201/bai-viet-nganh-USSH122_1270_anhtintuc.jpg" alt="Đại học xã hội và nhân văn" title="Đại học xã hội nhân văn">
        <br />

    </fieldset>
    <fieldset>
        <h1><div id="div1">Các trường ĐH Ở các tỉnh khác</div></h1>
        <br />
        <br />
        <br />
        <h3><a href="https://duytan.edu.vn/" class="class1">Duy tân University TP đà nằng</a></h3>
        <img width="300px" src="https://cdn.duytan.edu.vn/upload/images/23-Dai-Hoc-Duy-Tan.jpg" alt="duy tân University" title="duy University">
        <br />
        <h3><a href="https://www.ntu.edu.vn/"class="class1"> nha trang University</a></h3>
        <img width="300px" src="https://baokhanhhoa.vn/dataimages/201712/original/images5318937_dhnt.jpg" alt="Nha trang University" title="Nha trang University">
        <br />
        <h3><a href="https://qnu.edu.vn/" class="class1"> Quy Nhơn University</a></h3>
        <img width="300px" src="https://nld.mediacdn.vn/291774122806476800/2021/7/11/dai-hoc-quy-nhon-1625970223477332274135.jpg" alt="Quy nhơn University" title="Quy nhơn University">
         <br />
        <h3><a href="http://ukh.edu.vn/" class="class1"> Khánh Hòa University</a></h3> 
        <img width="300px" src="https://tuyensinhso.vn/images/files/tuyensinhso.com/truong-dai-hoc-khanh-hoa.JPG" alt="khánh hòa University" title="khánh hòa University">
        <br />
        <h3><a href="https://hueuni.edu.vn/portal/vi/"class="class1"> Huế University</a></h3>
        <img width="300px" src="https://hueuni.edu.vn/portal/vi/data/ntahuucas/20200805_092326_HNS_2271_copy.jpg" alt="Huế Unversity" title="Huế University">
        <br />
        <h3><a href="https://tuyensinh.yersin.edu.vn/"class="class1"> yersin University Đà Lạt</a></h3>
        <img width="300px" src="https://huongnghiepcdm.edu.vn/files/upload/files/dhyersindalat.jpeg" alt="yersi University" title="yersi University">
        <br />
        <h3><a href="https://donga.edu.vn/" class="class1">Đại học Đông á</a></h3>
        <img width="300px" src="https://nguoilambao.vn/upload_images/images/dai-hoc-dong-a.jpg" alt="Đại học Đông á" title="Đại học Đông á">
    </fieldset>

    
</body>
</html>
